export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as Services} from "./Services"
export {default as Documents} from "./Documents"
export {default as Contacts} from "./Contacts"